# deploy to github page github action
name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: "npm install"
        run: npm i
      - name: "npm build"
        run: npm run build
      - name: "ls"
        run: ls
      - name: "ls build"
        run: ls ./build
      - uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build
