# deploy to github page github action
name: Deploy to Github Pages
on:
  push:
    branches:
      - master
    paths:
      - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v2
        with:
          node-version: 12.18.3
      - name: "npm build"
        run: npm run build
      - name: "npm deploy"
        run: npm run deploy